server:
  port: 29091
feign:
  hystrix:
    enabled: true
  httpclient: ### 配置使用 ApacheHttpClient
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: false
        service-name: school-consumer
  application:
    name: school-service-consumer