spring:
  application:
    name: spring-cloud-gateway-service
  cloud:
    consul:
      discovery:
        register: true
      host: localhost
      port: 8500
    gateway:
      routes:
        - id: service-provider1
          uri: lb://service-provider1
          predicates:
            - Path=/service-provider1/*
          filters:
            - StripPrefix=1

server:
  port: 9091

