spring:
  application:
    name: spring-cloud-gateway-service
  cloud:
    consul:
      discovery:
        register: true
      host: localhost
      port: 8500
    gateway:
      routes:
        - id:service-producer1
            uri: lb://spring-cloud-service-provider1
            predicates:
              - path:=/service-p1/*

server:
  port: 9091

